rails:
  build: "docker"
  volumes:
    - "${RAILS_DIR}:/app"
    - "${SSL_CER_FILE}:/etc/ssl/conpinion-customerportal.cer"
    - "${SSL_KEY_FILE}:/etc/ssl/conpinion-customerportal.key"
  environment:
    - "RAILS_ENV=production"
    - "RAILS_SERVE_STATIC_FILES=yes"
    - "SECRET_KEY_BASE=${SECRET_KEY_BASE}"
    - "MAILER_SMTP_USER_NAME=${MAILER_SMTP_USER_NAME}"
    - "MAILER_SMTP_PASSWORD=${MAILER_SMTP_PASSWORD}"
    - "SIMPLEWEBRTC_URL=${SIMPLEWEBRTC_URL}"
    - "CABLE_URL=${CABLE_URL}"
    - "LICENSE_SIGNKEY_PRIV=${LICENSE_SIGNKEY_PRIV}"
    - "LICENSE_SIGNKEY_PUB=${LICENSE_SIGNKEY_PUB}"
    - "PAPERCLIP_STORAGE_QOUTA=${PAPERCLIP_STORAGE_QOUTA}"
  mem_limit: "512m"

webrtc:
  image: "voduytuan/tc-webrtc-signaling"
  volumes:
    - "${SIMPLEWEBRTC_PEM_FILE}:/src/certssl/site.pem"
  mem_limit: "64m"
